### ISSUE TITLE
In Firefox 60.x, after clear all history, the negotiator custom filters are also deleted.

### ISSUE THREAD

**Issue by kdwll** [hultqvist/negotiator#36]
I recently noticed that when I clear all Firefox history, restart the browser, my custom filters disappeared, negotiator's settings have also been reset. Here is my current system:

Windows 7 Pro 64bit
Firefox 60.2.1esr 64bit
Negotiator 0.0.8.4

There are two other minor issues:

In Firefox 60.x, negotiator's icon is displayed in the address bar, can it be moved to the toolbar? like this:

https://i.imgur.com/hCwPMKQ.png

In Firefox extensions page, add an "Options" button. like this:

https://i.imgur.com/lpE0esw.png

The Negotiator is a simple and powerful extension that supports both firefox and chrome. All users who value browser security should install this extension. Thank you very much for your work!

**Comment by hultqvist** [comment]
Settings shouldn't ever be deleted unless there was a checkbox in you clear dialog that explicitly says "delete extension data", I need to look more into this.

At the last release for Firefox, Firefox for Android only supported that icon location.
That was some time ago so I will look into what has changed since then,

The options page works in Chrome so I need to look into why Firefox is not recognising it.

**Comment by hultqvist** [comment]
* Desktop version is now using the browserAction/toolbar icon.
* Options button is now working.

I've fixed one bug where settings was lost because of a dead object.
Clearing history might have been a coincidence.

Please check version 0.0.9.0 and reopen if it's still an issue.
